### ISSUE TITLE
DB 마이그레이션 라이브러리 추가

### ISSUE THREAD

**Issue by zoripong** [k-roffle/knitting-service#8]
데이터베이스 마이그레이션 관리를 위해 라이브러리를 추가합니다.

**Comment by zoripong** [comment]
1번째 생각해본 라이브러리: flyway
ref: https://www.baeldung.com/database-migrations-with-flyway

**Comment by zoripong** [comment]
확인해보니 liquibase 라는 라이브러리도 있는 것 같습니다.
liquibase 는 diff generation 이 가능하고 rollback이 가능하다는 장점이 있는데
xml을 기반으로 관리하고 (...) github star 수로 사용자를 추정해봤을 때 flyway가 좀 더 많이 사용하고 있는 것 같아서 flyway를 이어서 쓰도록 하겠습니다

ref: https://dzone.com/articles/flyway-vs-liquibase
ref: https://blog.gangnamunni.com/post/introducing-flyway/

**Comment by zoripong** [comment]
undo 라는 명령어가 있어서 괜찮을 것 같네요?!

ref: https://flywaydb.org/documentation/getstarted/advanced/undo

**Comment by zoripong** [comment]
https://github.com/KenjiOhtsuka/harmonica

이것이 가장 좋아보이군요 ✨ 👀 

python에서 자주 쓰던 alembic이랑 아주 많이 비슷하고 kotlin 으로 마이그레이션 스크립트를 짤 수 있는 것이 아-주 매력적이네용
우려되는 부분은 많이 사용되지 않는 것 같네요 ㅠㅠ

**Comment by YuuRiLee** [comment]
이슈 관리만 제대로 되고 있다면 좋아요

**Comment by kimdoori** [comment]
토이 프로젝트이므로 사용해보고 싶은 거 사용해도 괜찮다고 생각합니다 ㅎㅎ 끌리는 거 사용하시죠!
